<?php
declare(strict_types=1);

require_once __DIR__ . '/includes/bootstrap.php';

header('Content-Type: text/plain; charset=utf-8');

$lines = [
    '# robots.txt for ' . store_name(),
    '# Generated by robots.php so the sitemap URL always matches the live domain.',
    '',
    'User-agent: *',
    'Allow: /',
    '',
    '# Never block CSS, JS, fonts or images - Googlebot must render the pages.',
    'Allow: /assets/',
    '',
    '# Transactional / duplicate pages:',
    'Disallow: /cart/',
    'Disallow: /checkout/',
    'Disallow: /account/',
    'Disallow: /wishlist/',
    'Disallow: /order/',
    'Disallow: /search/',
    'Disallow: /admin/',
    'Disallow: /api/',
    'Disallow: /install.php',
    'Disallow: /.backup-html/',
    'Disallow: /db/',
    'Disallow: /tools/',
    '',
    '# Faceted navigation and crawl traps (infinite parameter combinations):',
    'Disallow: /*?sort=',
    'Disallow: /*?q=',
    'Disallow: /*?price=',
    'Disallow: /*?color=',
    'Disallow: /*?size=',
    'Disallow: /*?filter=',
    'Disallow: /*&sort=',
    'Disallow: /*&q=',
    'Disallow: /*&price=',
    'Disallow: /*&color=',
    'Disallow: /*&size=',
    'Disallow: /*&filter=',
    '',
    'Sitemap: ' . url_abs('sitemap.xml'),
    '',
];

echo implode("\n", $lines);
