<?php
declare(strict_types=1);

/*
 * CLI-only. nginx does not read .htaccess, so these utilities must refuse to
 * run over HTTP themselves rather than relying on server configuration.
 */
if (PHP_SAPI !== 'cli') {
    http_response_code(403);
    header('Content-Type: text/plain; charset=utf-8');
    exit('This script can only be run from the command line.');
}

/**
 * Arail product catalogue seed (generated from the Shop page + live category pages).
 * Imported only when the products table is empty.
 */
return [
    'categories' => [
        ['slug' => 'injectable-anabolics', 'name' => 'Injectable Anabolics', 'sort_order' => 1],
        ['slug' => 'oral-anabolics', 'name' => 'Oral Anabolics', 'sort_order' => 2],
        ['slug' => 'peptides-hgh', 'name' => 'Peptides & HGH', 'sort_order' => 3],
    ],
    'products' => [
        ['slug' => 'test-cyp-200', 'name' => 'TEST CYP-200', 'price' => 40.00, 'image' => 'assets/img/diwone-test-cyp-200-600x600.png', 'category' => 'injectable-anabolics', 'featured' => 1, 'description' => 'TEST CYP-200 by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'test-enanthate-300', 'name' => 'TEST ENANTHATE-300', 'price' => 45.00, 'image' => 'assets/img/diowne-test-e-600x600.png', 'category' => 'injectable-anabolics', 'featured' => 1, 'description' => 'TEST ENANTHATE-300 by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'equipose-300', 'name' => 'EQUIPOISE-300', 'price' => 45.00, 'image' => 'assets/img/diwone-eq-600x600.png', 'category' => 'injectable-anabolics', 'featured' => 1, 'description' => 'EQUIPOISE-300 by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'tren-acetate-100', 'name' => 'TREN ACETATE-100', 'price' => 45.00, 'image' => 'assets/img/diwone-tren-a-600x600.png', 'category' => 'injectable-anabolics', 'featured' => 1, 'description' => 'TREN ACETATE-100 by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'sustanon-250', 'name' => 'SUSTANON-250', 'price' => 45.00, 'image' => 'assets/img/diwone-sust-250-600x600.png', 'category' => 'injectable-anabolics', 'featured' => 1, 'description' => 'SUSTANON-250 by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'test-prop-100', 'name' => 'TEST PROP-100', 'price' => 30.00, 'image' => 'assets/img/diwone-test-p-600x600.png', 'category' => 'injectable-anabolics', 'featured' => 1, 'description' => 'TEST PROP-100 by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'bacteriostatic-water-10ml', 'name' => 'Bacteriostatic Water 10ML', 'price' => 8.00, 'image' => 'assets/img/diwone-bac-water-white-600x600.png', 'category' => 'peptides-hgh', 'featured' => 0, 'description' => 'Bacteriostatic Water 10ML by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'mast-prop-100', 'name' => 'MAST PROP-100', 'price' => 60.00, 'image' => 'assets/img/diwone-mast-p-600x600.png', 'category' => 'injectable-anabolics', 'featured' => 1, 'description' => 'MAST PROP-100 by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'retatrutide-10mg', 'name' => 'Retatrutide 10MG', 'price' => 45.00, 'image' => 'assets/img/diwone-reta-10-600x600.png', 'category' => 'peptides-hgh', 'featured' => 0, 'description' => 'Retatrutide 10MG by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'hcg-10000iu', 'name' => 'HCG 10000IU', 'price' => 60.00, 'image' => 'assets/img/diwone-hcg-10000iu-600x600.png', 'category' => 'peptides-hgh', 'featured' => 0, 'description' => 'HCG 10000IU by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'nandrolone-prop-100', 'name' => 'NANDROLONE PROP-100', 'price' => 40.00, 'image' => 'assets/img/diwone-npp-600x600.png', 'category' => 'injectable-anabolics', 'featured' => 1, 'description' => 'NANDROLONE PROP-100 by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'arimidex-1', 'name' => 'ARIMIDEX-1 (Alcohol Based)', 'price' => 25.00, 'image' => 'assets/img/ARIMIDEX30ML-DROP-2-600x600.png', 'category' => 'oral-anabolics', 'featured' => 0, 'description' => 'ARIMIDEX-1 (Alcohol Based) by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'superdrol-40', 'name' => 'SUPERDROL 40 (NO SUPER SOLVENTS) in Mig840', 'price' => 40.00, 'image' => 'assets/img/diwone-superdrol-inj-600x600.png', 'category' => 'injectable-anabolics', 'featured' => 1, 'description' => 'SUPERDROL 40 (NO SUPER SOLVENTS) in Mig840 by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'tren-enanthate-200', 'name' => 'TREN ENANTHATE-200', 'price' => 70.00, 'image' => 'assets/img/diwone-tren-e-600x600.png', 'category' => 'injectable-anabolics', 'featured' => 1, 'description' => 'TREN ENANTHATE-200 by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'nandrolone-deca-300', 'name' => 'NANDROLONE DECA-300', 'price' => 45.00, 'image' => 'assets/img/diwone-deca-600x600.png', 'category' => 'injectable-anabolics', 'featured' => 1, 'description' => 'NANDROLONE DECA-300 by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'test-cyp-50mg-ml', 'name' => 'Test Cyp-50MG/ML', 'price' => 25.00, 'image' => 'assets/img/diwone-test-cyp-50-600x600.png', 'category' => 'injectable-anabolics', 'featured' => 1, 'description' => 'Test Cyp-50MG/ML by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'l-carnitine-500mg-ml', 'name' => 'L-Carnitine-500MG/ML', 'price' => 25.00, 'image' => 'assets/img/diwone-l-carnitine-600x600.png', 'category' => 'injectable-anabolics', 'featured' => 0, 'description' => 'L-Carnitine-500MG/ML by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'test-cyp-gso', 'name' => 'GSO Test Cyp-200', 'price' => 40.00, 'image' => 'assets/img/diwone-test-cyp-gso-600x600.png', 'category' => 'injectable-anabolics', 'featured' => 0, 'description' => 'GSO Test Cyp-200 by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'winstrol-25', 'name' => 'WINSTROL-25', 'price' => 65.00, 'image' => 'assets/img/WINSTROL25-100-2-600x600.png', 'category' => 'oral-anabolics', 'featured' => 0, 'description' => 'WINSTROL-25 by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'glutathione-200mg-ml', 'name' => 'l-Glutathione 1,500MG', 'price' => 40.00, 'image' => 'assets/img/arail-l-glutathione-box-vial-1-600x600.png', 'category' => 'peptides-hgh', 'featured' => 0, 'description' => 'l-Glutathione 1,500MG by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'clenbuterol-250mcg', 'name' => 'CLENBUTEROL-150MCG (Alcohol Based)', 'price' => 25.00, 'image' => 'assets/img/diwone-clen-600x600.png', 'category' => 'oral-anabolics', 'featured' => 0, 'description' => 'CLENBUTEROL-150MCG (Alcohol Based) by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'estradiol-cypionate-10mg-ml', 'name' => 'Estradiol Cypionate-10MG/ML', 'price' => 25.00, 'image' => 'assets/img/diwone-estradiol-cyp-white-600x600.png', 'category' => 'injectable-anabolics', 'featured' => 0, 'description' => 'Estradiol Cypionate-10MG/ML by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'helios', 'name' => 'Helios+', 'price' => 35.00, 'image' => 'assets/img/diwone-helios-white-600x600.png', 'category' => 'injectable-anabolics', 'featured' => 0, 'description' => 'Helios+ by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'methyltrienolone-3-mtren', 'name' => 'Methyltrienolone-3 (Mtren) (NO SUPER SOLVENTS) in Mig840', 'price' => 50.00, 'image' => 'assets/img/diwone-mtr-600x600.png', 'category' => 'injectable-anabolics', 'featured' => 0, 'description' => 'Methyltrienolone-3 (Mtren) (NO SUPER SOLVENTS) in Mig840 by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'dbol-50mg-ml-no-super-solvents', 'name' => 'Dbol 50MG/ML (NO SUPER SOLVENTS) in Mig840', 'price' => 40.00, 'image' => 'assets/img/diwone-dbol-inj-600x600.png', 'category' => 'injectable-anabolics', 'featured' => 0, 'description' => 'Dbol 50MG/ML (NO SUPER SOLVENTS) in Mig840 by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'cytomel-100mcg', 'name' => 'CYTOMEL-100MCG (Alcohol Based)', 'price' => 25.00, 'image' => 'assets/img/CYTOMEL30ML-DROP-2-600x600.png', 'category' => 'oral-anabolics', 'featured' => 0, 'description' => 'CYTOMEL-100MCG (Alcohol Based) by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'tirzepatide', 'name' => 'Tirzepatide 10MG', 'price' => 40.00, 'image' => 'assets/img/diwone-tirz-10-600x600.png', 'category' => 'peptides-hgh', 'featured' => 0, 'description' => 'Tirzepatide 10MG by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'nolvadex-20', 'name' => 'NOLVADEX-20', 'price' => 55.00, 'image' => 'assets/img/NOVALDEX20-100-2-600x600.png', 'category' => 'oral-anabolics', 'featured' => 0, 'description' => 'NOLVADEX-20 by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'bpc-157-5mg', 'name' => 'BPC-157 5MG', 'price' => 30.00, 'image' => 'assets/img/diwone-bpc-157-white-600x600.png', 'category' => 'peptides-hgh', 'featured' => 0, 'description' => 'BPC-157 5MG by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'tne-100-no-super-solvents-in-mig840', 'name' => 'TNE-100 (NO SUPER SOLVENTS) in Mig840', 'price' => 40.00, 'image' => 'assets/img/diwone-TNE-100-white-600x600.png', 'category' => 'injectable-anabolics', 'featured' => 0, 'description' => 'TNE-100 (NO SUPER SOLVENTS) in Mig840 by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'mast-enanthate-200', 'name' => 'MAST ENANTHATE-200', 'price' => 120.00, 'image' => 'assets/img/diwone-mast-e-600x600.png', 'category' => 'injectable-anabolics', 'featured' => 0, 'description' => 'MAST ENANTHATE-200 by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'dianabol-10', 'name' => 'DIANABOL-25', 'price' => 65.00, 'image' => 'assets/img/DIANABOL25-100TABS-2-600x600.png', 'category' => 'oral-anabolics', 'featured' => 0, 'description' => 'DIANABOL-25 by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 't4', 'name' => 'T4 (Alcohol Based)', 'price' => 25.00, 'image' => 'assets/img/THYROXINE-2-600x600.png', 'category' => 'oral-anabolics', 'featured' => 0, 'description' => 'T4 (Alcohol Based) by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'clomid-50', 'name' => 'CLOMID-25', 'price' => 65.00, 'image' => 'assets/img/CLOMID25-100TABS-2-600x600.png', 'category' => 'oral-anabolics', 'featured' => 0, 'description' => 'CLOMID-25 by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'mt2-10mg', 'name' => 'MT2 10MG', 'price' => 30.00, 'image' => 'assets/img/diwone-mt2-white-600x600.png', 'category' => 'peptides-hgh', 'featured' => 0, 'description' => 'MT2 10MG by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'proviron-25', 'name' => 'PROVIRON-25', 'price' => 120.00, 'image' => 'assets/img/PROVIRON25-100-2-600x600.png', 'category' => 'oral-anabolics', 'featured' => 0, 'description' => 'PROVIRON-25 by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'superdrol-10', 'name' => 'SUPERDROL 10', 'price' => 65.00, 'image' => 'assets/img/SUPERDROL10-100-2-600x600.png', 'category' => 'oral-anabolics', 'featured' => 0, 'description' => 'SUPERDROL 10 by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'tb-500-5mg', 'name' => 'TB-500 5MG', 'price' => 30.00, 'image' => 'assets/img/diwone-tb500-white-600x600.png', 'category' => 'peptides-hgh', 'featured' => 0, 'description' => 'TB-500 5MG by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'retatrutide-60mg', 'name' => 'Retatrutide 60MG', 'price' => 90.00, 'image' => 'assets/img/diwone-reta-60-600x600.png', 'category' => 'peptides-hgh', 'featured' => 0, 'description' => 'Retatrutide 60MG by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'klow-80mg', 'name' => 'KLOW 80MG', 'price' => 80.00, 'image' => 'assets/img/diwone-klow-600x600.png', 'category' => 'peptides-hgh', 'featured' => 0, 'description' => 'KLOW 80MG by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'pt-141-10mg', 'name' => 'PT-141 10MG', 'price' => 40.00, 'image' => 'assets/img/diwone-pt-141-600x600.png', 'category' => 'peptides-hgh', 'featured' => 0, 'description' => 'PT-141 10MG by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'tirzepatide-30mg', 'name' => 'Tirzepatide 30MG', 'price' => 70.00, 'image' => 'assets/img/diwone-tirz-30-600x600.png', 'category' => 'peptides-hgh', 'featured' => 0, 'description' => 'Tirzepatide 30MG by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'ghk-cu-50mg', 'name' => 'GHK-CU 50MG', 'price' => 40.00, 'image' => 'assets/img/dwione-ghk-cu-600x600.png', 'category' => 'peptides-hgh', 'featured' => 0, 'description' => 'GHK-CU 50MG by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'nandrolone-prop-200-mig840-no-super-solvents', 'name' => 'NANDROLONE PROP-200 (MIG840 NO SUPER SOLVENTS)', 'price' => 80.00, 'image' => 'assets/img/diwone-npp-200-600x600.jpeg', 'category' => 'injectable-anabolics', 'featured' => 0, 'description' => 'NANDROLONE PROP-200 (MIG840 NO SUPER SOLVENTS) by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'glow-70mg', 'name' => 'GLOW 70MG', 'price' => 70.00, 'image' => 'assets/img/diwone-glow-600x600.png', 'category' => 'peptides-hgh', 'featured' => 0, 'description' => 'GLOW 70MG by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'semaglutide-10mg', 'name' => 'Semaglutide 10MG', 'price' => 70.00, 'image' => 'assets/img/diwone-sema-10-600x600.png', 'category' => 'peptides-hgh', 'featured' => 0, 'description' => 'Semaglutide 10MG by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'ipamorelin-10mg', 'name' => 'Ipamorelin 10MG', 'price' => 50.00, 'image' => 'assets/img/diwone-ipa-600x600.png', 'category' => 'peptides-hgh', 'featured' => 0, 'description' => 'Ipamorelin 10MG by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'arail-somatropin-100iu', 'name' => 'Arail Somatropin 100IU', 'price' => 130.00, 'image' => 'assets/img/diwone-hgh-100iu-scaled-600x600.png', 'category' => 'peptides-hgh', 'featured' => 0, 'description' => 'Arail Somatropin 100IU by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'semaglutide-5mg', 'name' => 'Semaglutide 5MG', 'price' => 40.00, 'image' => 'assets/img/diwone-sema-5-600x600.png', 'category' => 'peptides-hgh', 'featured' => 0, 'description' => 'Semaglutide 5MG by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
        ['slug' => 'arail-somatropin-240iu', 'name' => 'Arail Somatropin 240IU', 'price' => 230.00, 'image' => 'assets/img/diwone-hgh-240iu-scaled-600x600.png', 'category' => 'peptides-hgh', 'featured' => 0, 'description' => 'Arail Somatropin 240IU by Arail Pharmaceuticals. Independently lab-tested for purity and potency.'],
    ],
];
