<?php
declare(strict_types=1);

/**
 * Front-end bootstrap: wires the shared libraries together for every public
 * page. No framework, no output.
 */

// Read .env first: the runtime flags below and every value in config.php are
// read with getenv(). See includes/env.php.
require_once __DIR__ . '/env.php';
arail_load_env();

require_once __DIR__ . '/db.php';
require_once __DIR__ . '/helpers.php';
require_once __DIR__ . '/seo.php';
require_once __DIR__ . '/catalog.php';

// Security headers + CSP. They cannot live in .htaccess: nginx ignores it and
// phpix (Wasmer Edge) refuses the `Header` directive outright. See helpers.php.
arail_send_security_headers();

// Production-safe error handling: never display errors to visitors.
if ((getenv('APP_DEBUG') ?: '') !== '1') {
    ini_set('display_errors', '0');
    error_reporting(E_ALL & ~E_DEPRECATED & ~E_NOTICE & ~E_WARNING);
}

/** Root-relative URL for a file inside /assets. */
function asset(string $path): string
{
    return url_path('assets/' . ltrim($path, '/'));
}

/** HTML-escape helper alias used by templates. */
function h($value): string
{
    return e($value);
}

/**
 * Render the class list for a primary-nav item, highlighting the active page.
 */
function nav_classes(string $key, string $active): string
{
    $base = 'site-header-link rounded-full px-3 py-2 text-[13px] font-medium tracking-[-0.01em] outline-none transition-colors sm:px-3.5 sm:text-[14px] ';
    return $base . ($key === $active
        ? 'bg-[var(--accent-soft)] text-[var(--accent-dark)]'
        : 'text-[var(--ink)] hover:bg-[var(--surface-soft)] hover:text-[var(--accent-dark)]');
}

/** Class list for a mobile-menu item. */
function nav_mobile_classes(string $key, string $active): string
{
    $base = 'rounded-[14px] px-4 py-3 text-[15px] font-medium tracking-[-0.01em] outline-none transition-colors focus-visible:ring-2 focus-visible:ring-[var(--accent)] ';
    return $base . ($key === $active
        ? 'bg-[var(--accent-soft)] text-[var(--accent-dark)]'
        : 'text-[var(--ink)] hover:bg-[var(--surface-soft)] hover:text-[var(--accent-dark)]');
}

/**
 * WebP sibling for a locally stored image, or null when none exists.
 * Generated by tools/optimize-images.php.
 */
function image_webp(?string $stored): ?string
{
    $stored = trim((string)$stored);
    if ($stored === '' || str_starts_with($stored, 'uploads/') || preg_match('~^https?://~i', $stored)) {
        return null;
    }
    $base = basename($stored);
    if (!preg_match('~\.(png|jpe?g)$~i', $base)) {
        return null;
    }
    $webpName = preg_replace('~\.(png|jpe?g)$~i', '.webp', $base);
    if (!is_file(dirname(__DIR__) . '/assets/img/' . $webpName)) {
        return null;
    }
    return url_path('assets/img/' . $webpName);
}

/**
 * Render an image (or <picture> with a WebP source) with escaped attributes.
 *
 * @param array<string,string|int> $attrs extra attributes, e.g. ['width' => 600]
 */
function picture(?string $stored, string $alt, array $attrs = []): string
{
    $img  = image_url($stored);
    $webp = image_webp($stored);

    $attrString = '';
    foreach ($attrs as $key => $value) {
        $attrString .= ' ' . $key . '="' . e((string)$value) . '"';
    }

    $imgTag = '<img src="' . e($img) . '" alt="' . e($alt) . '"' . $attrString . '>';
    if ($webp) {
        return '<picture><source type="image/webp" srcset="' . e($webp) . '">' . $imgTag . '</picture>';
    }
    return $imgTag;
}

/** Thousands-separated money string for the configured currency. */
function format_money(float $amount): string
{
    return currency_symbol() . number_format($amount, 2);
}
